sudo: required
env:
  - CI=true
services:
  - docker

before_install:
  - docker build -t drnikon/docker-react -f Dockerfile.dev .

script:
  - docker run drnikon/docker-react CI=true npm run test -- --coverage
